### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by KurtPachinger** [KurtPachinger/vis-audio#1]
### bug
- [ ] y-oscillator render rotation is not in sync
- [ ] demo: `ux` > `update` > `tween` may affect FPS onPageLoad due to multiple queued events. Began after using time-based tween and not frame.
- [ ] peaks shadows look 90-degrees off initially
- [ ] camera tween blocks raycast
- [ ] WebAudio rings when turned up

### enhancement
- [ ] peaks (power-of-two) create fractal chains
![catmull](https://user-images.githubusercontent.com/48163461/221284759-d63aefe6-519a-4fda-8963-68bcb3fda837.png)
![fractal](https://user-images.githubusercontent.com/48163461/221284757-41a7b8c0-fef7-4d2c-bd75-96fd5f68ecc5.png)
